#!/usr/bin/env bash
# Quick reference for deploy.sh usage

cat << 'EOF'
╔════════════════════════════════════════════════════════════════╗
║                                                                ║
║        NetBox DCIM/IPAM LXC - Deployment Quick Reference       ║
║                                                                ║
╚════════════════════════════════════════════════════════════════╝

BASIC USAGE
───────────────────────────────────────────────────────────────
  ./deploy.sh              # Interactive menu
  ./deploy.sh deploy       # Full deployment (Terraform + Ansible)
  ./deploy.sh plan         # Dry-run (preview changes)
  ./deploy.sh status       # Check deployment status
  ./deploy.sh destroy      # Destroy infrastructure
  ./deploy.sh help         # Show help

ADVANCED USAGE
───────────────────────────────────────────────────────────────
  ./deploy.sh checks       # Pre-flight checks only
  ./deploy.sh terraform    # Terraform workflow only
  ./deploy.sh ansible      # Ansible workflow only

PREREQUISITES
───────────────────────────────────────────────────────────────
⚠️  HashiCorp Vault REQUIRED (deploy lxc_vault first)
    See: ../lxc_vault/README.md

VAULT AUTHENTICATION
───────────────────────────────────────────────────────────────
Required Environment Variables:
  VAULT_ADDR='https://vault.example.com:8200'
  VAULT_USERNAME='terraform'
  VAULT_PASSWORD='your-vault-password'

Or use vault_init.sh (recommended):
  cd terraform
  source ./vault_init.sh  # Handles Vault auth + AWS creds

NETBOX SERVICES
───────────────────────────────────────────────────────────────
Check all services:
  ssh ansible@<container-ip>
  sudo systemctl status postgresql redis-server netbox netbox-rq nginx

View logs:
  sudo journalctl -u netbox -f
  sudo journalctl -u postgresql -f
  tail -f /var/log/nginx/error.log

QUICK SETUP
───────────────────────────────────────────────────────────────
1. Configure vault_init.sh:
   cd terraform
   cp vault_init.sh.example vault_init.sh
   vim vault_init.sh  # Set VAULT_ADDR, VAULT_USERNAME

2. Configure Terraform:
   cp terraform.tfvars.example terraform.tfvars
   vim terraform.tfvars

3. Configure S3 backend:
   cp s3.backend.config.template s3.backend.config
   vim s3.backend.config

4. Configure Ansible inventory (after deployment):
   cd ../ansible
   cp inventory.yml.example inventory.yml
   # Edit with container IP from terraform output

ACCESSING NETBOX
───────────────────────────────────────────────────────────────
Web Interface:
  http://\<container-ip\>/        # Port 80 (default)
  http://\<container-ip\>:8300/   # Port 8300 (if 80 in use)

Admin Credentials:
  Username: admin
  Password: vault kv get secrets/proxmox/netbox

COMMON COMMANDS
───────────────────────────────────────────────────────────────
# Get container IP
cd terraform && tofu output lxc_ip_address

# SSH to container
ssh ansible@<container-ip>

# Restart NetBox services
sudo systemctl restart netbox netbox-rq

# View NetBox version
/opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py version

# Django management
cd /opt/netbox
sudo -u netbox /opt/netbox/venv/bin/python netbox/manage.py <command>

VAULT SECRETS PATHS
───────────────────────────────────────────────────────────────
Required in Vault KV:
  secrets/proxmox/api_token
  secrets/proxmox/ssh_keys/root_public
  secrets/proxmox/ssh_keys/ansible_public
  secrets/proxmox/node_name
  secrets/proxmox/netbox/db_password

Auto-generated by Ansible:
  secrets/proxmox/netbox/secret_key
  secrets/proxmox/netbox/django_superuser_password

TROUBLESHOOTING
───────────────────────────────────────────────────────────────
# Test Vault connectivity
vault status

# Verify Vault secrets exist
vault kv list secrets/proxmox

# Check Terraform state encryption
vault read transit/keys/terraform-state-encryption

# Test all services
ansible netbox -i ansible/inventory.yml -m shell \
  -a "systemctl is-active postgresql redis-server netbox netbox-rq nginx" -b

# View deployment logs
tail -f logs/deployment_*.log

LINKS
───────────────────────────────────────────────────────────────
Documentation:  README.md
Deployment:     DEPLOYMENT.md
Vault Setup:    ../lxc_vault/README.md
NetBox Docs:    https://docs.netbox.dev/

EOF
