#!/usr/bin/env bash
# =============================================================================
# Ansible Functions for LXC Base Template
# =============================================================================

# Prevent multiple sourcing
[[ -n "${_ANSIBLE_SH_LOADED:-}" ]] && return 0
_ANSIBLE_SH_LOADED=1

# Create inventory from Terraform outputs
ansible_create_inventory() {
    log_info "Creating Ansible inventory from Terraform outputs..."
    
    local container_ip
    container_ip=$(terraform_get_output "lxc_ip_address" 2>/dev/null)
    
    if [[ -z "${container_ip}" || "${container_ip}" == "null" ]]; then
        log_error "Could not get container IP from Terraform"
        return 1
    fi

    # Strip CIDR notation if present
    container_ip="${container_ip%%/*}"
    log_info "Container IP: ${container_ip}"

    cat > "${ANSIBLE_DIR}/inventory.yml" <<EOF
# Generated by deploy.sh at $(date)
all:
  children:
    container:
      hosts:
        grafana:
          ansible_host: ${container_ip}
          ansible_port: 22
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_become: true
        ansible_become_method: sudo
EOF

    log_success "Created: ${ANSIBLE_DIR}/inventory.yml"
    return 0
}

# Test connectivity
ansible_test() {
    log_info "Testing Ansible connectivity..."
    cd "${ANSIBLE_DIR}" || return 1

    if [[ ! -f "inventory.yml" ]]; then
        log_error "inventory.yml not found"
        return 1
    fi

    if ansible container -m ping -i inventory.yml | tee -a "${LOG_FILE}"; then
        log_success "Connectivity OK"
        return 0
    else
        log_error "Connectivity failed"
        return 1
    fi
}

# Run playbook
ansible_deploy() {
    log_header "Running Ansible Playbook"
    cd "${ANSIBLE_DIR}" || return 1

    if [[ ! -f "inventory.yml" ]]; then
        log_info "Creating inventory..."
        ansible_create_inventory || return 1
    fi

    # VAULT_TOKEN is passed via environment variable (not command line for security)
    if [[ -z "${VAULT_TOKEN:-}" ]]; then
        log_warning "VAULT_TOKEN not set - Vault lookups may fail"
    fi

    # Grafana admin password handling
    # Check if password is provided via environment variable
    if [[ -z "${GRAFANA_ADMIN_PASSWORD:-}" ]]; then
        log_info "Grafana admin password not set in environment"
        log_info "Please enter the Grafana admin password (input will be hidden)"
        
        # Read password securely (hidden input)
        read -s -p "Grafana admin password: " GRAFANA_ADMIN_PASSWORD
        echo  # Newline after hidden input
        
        # Validate password is not empty
        if [[ -z "${GRAFANA_ADMIN_PASSWORD}" ]]; then
            log_error "Password cannot be empty"
            log_info "Set GRAFANA_ADMIN_PASSWORD environment variable or provide it when prompted"
            return 1
        fi
        
        log_success "Password received"
    else
        log_info "Using GRAFANA_ADMIN_PASSWORD from environment"
    fi

    log_info "Running: ansible-playbook -i inventory.yml site.yml"

    # Export variables so Ansible can access them via environment
    export VAULT_TOKEN
    export GRAFANA_ADMIN_PASSWORD
    
    if ansible-playbook -i inventory.yml site.yml | tee -a "${LOG_FILE}"; then
        log_success "Playbook complete"
        return 0
    else
        log_error "Playbook failed"
        return 1
    fi
}
