#!/usr/bin/env bash
# =============================================================================
# Ansible Functions for LXC Grafana Loki
# =============================================================================

# Prevent multiple sourcing
[[ -n "${_ANSIBLE_SH_LOADED:-}" ]] && return 0
_ANSIBLE_SH_LOADED=1

# Create inventory from Terraform outputs
ansible_create_inventory() {
    log_info "Creating Ansible inventory from Terraform outputs..."
    
    local container_ip
    local npm_ip_address
    local grafana_ip_address
    container_ip=$(terraform_get_output "lxc_ip_address" 2>/dev/null)
    npm_ip_address=$(grep "npm_ip_address" "${TERRAFORM_DIR}/terraform.tfvars" | grep -v "^#" | cut -d "=" -f 2 | tr -d ' ' | tr -d '"' | tr -d "'")
    grafana_ip_address=$(grep "grafana_ip_address" "${TERRAFORM_DIR}/terraform.tfvars" | grep -v "^#" | cut -d "=" -f 2 | tr -d ' ' | tr -d '"' | tr -d "'")
    
    if [[ -z "${container_ip}" || "${container_ip}" == "null" ]]; then
        log_error "Could not get container IP from Terraform"
        return 1
    elif [[ -z "${npm_ip_address}" || "${npm_ip_address}" == "null" ]]; then
        log_error "Could not get npm IP from Terraform"
        echo -n "Enter npm IP address: "
        read -r npm_ip_address
        [[ -z "${npm_ip_address}" ]] && { log_error "npm_ip_address required"; return 1; }
    elif [[ -z "${grafana_ip_address}" || "${grafana_ip_address}" == "null" ]]; then
        log_error "Could not get grafana IP from Terraform"
        echo -n "Enter grafana IP address: "
        read -r grafana_ip_address
        [[ -z "${grafana_ip_address}" ]] && { log_error "grafana_ip_address required"; return 1; }
    fi

    # Strip CIDR notation if present
    container_ip="${container_ip%%/*}"
    npm_ip_address="${npm_ip_address%%/*}"
    grafana_ip_address="${grafana_ip_address%%/*}"
    log_info "Container IP: ${container_ip}"
    log_info "npm IP: ${npm_ip_address}"
    log_info "grafana IP: ${grafana_ip_address}"

    cat > "${ANSIBLE_DIR}/inventory.yml" <<EOF
# Generated by deploy.sh at $(date)
all:
  children:
    container:
      hosts:
        grafana-loki:
          ansible_host: ${container_ip}
          ansible_port: 22
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_become: true
        ansible_become_method: sudo
        loki_firewall_allowed_sources:
          - ip: "${npm_ip_address}"
            comment: "NPM reverse proxy"
          - ip: "${grafana_ip_address}"
            comment: "Grafana data source"
EOF

    log_success "Created: ${ANSIBLE_DIR}/inventory.yml"
    return 0
}

# Test connectivity
ansible_test() {
    log_info "Testing Ansible connectivity..."
    cd "${ANSIBLE_DIR}" || return 1

    if [[ ! -f "inventory.yml" ]]; then
        log_error "inventory.yml not found"
        return 1
    fi

    if ansible container -m ping -i inventory.yml | tee -a "${LOG_FILE}"; then
        log_success "Connectivity OK"
        return 0
    else
        log_error "Connectivity failed"
        return 1
    fi
}

# Run playbook
ansible_deploy() {
    log_header "Running Ansible Playbook"
    cd "${ANSIBLE_DIR}" || return 1

    if [[ ! -f "inventory.yml" ]]; then
        log_info "Creating inventory..."
        ansible_create_inventory || return 1
    fi

    # VAULT_TOKEN is passed via environment variable (not command line for security)
    if [[ -z "${VAULT_TOKEN:-}" ]]; then
        log_warning "VAULT_TOKEN not set - Vault lookups may fail"
    fi

    log_info "Running: ansible-playbook -i inventory.yml site.yml"

    # Export VAULT_TOKEN so Ansible can access it via environment
    export VAULT_TOKEN
    
    if ansible-playbook -i inventory.yml site.yml | tee -a "${LOG_FILE}"; then
        log_success "Playbook complete"
        return 0
    else
        log_error "Playbook failed"
        return 1
    fi
}
