#!/usr/bin/env bash
# =============================================================================
# Ansible Functions for VM Docker Pool
# =============================================================================

# Prevent multiple sourcing
[[ -n "${_ANSIBLE_SH_LOADED:-}" ]] && return 0
_ANSIBLE_SH_LOADED=1

# Create inventory from Terraform outputs
ansible_create_inventory() {
    log_info "Creating Ansible inventory from Terraform outputs..."
    
    local vm_ip
    vm_ip=$(terraform_get_output "vm_ip_address" 2>/dev/null)
    
    if [[ -z "${vm_ip}" || "${vm_ip}" == "null" ]]; then
        log_error "Could not get VM IP from Terraform"
        return 1
    fi

    # Strip CIDR notation if present
    vm_ip="${vm_ip%%/*}"
    log_info "VM IP: ${vm_ip}"

    local portainer_data_path
    portainer_data_path=$(terraform_get_output "portainer_data_path" 2>/dev/null)
    portainer_data_path="${portainer_data_path:-/opt/portainer/data}"

    cat > "${ANSIBLE_DIR}/inventory.yml" <<EOF
# Generated by deploy.sh at $(date)
all:
  hosts:
    docker-pool:
      ansible_host: ${vm_ip}
      ansible_port: 22
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible
      ansible_python_interpreter: /usr/bin/python3

  vars:
    # Base role variables
    base_timezone: "UTC"
    base_locale: "en_US.UTF-8"
    
    # SSH hardening
    ssh_permit_root_login: "no"
    ssh_password_authentication: "no"
    ssh_pubkey_authentication: "yes"
    
    # UFW firewall ports
    ufw_allowed_ports:
      - { port: 22, proto: tcp, comment: "SSH" }
      - { port: 9443, proto: tcp, comment: "Portainer HTTPS" }
    
    # Docker role variables
    docker_edition: "ce"
    docker_users:
      - ansible
    
    # Docker daemon configuration
    docker_daemon_options:
      log-driver: "json-file"
      log-opts:
        max-size: "10m"
        max-file: "3"
      storage-driver: "overlay2"
      live-restore: true
      userland-proxy: false
    
    # Portainer role variables
    portainer_image: "portainer/portainer-ce:latest"
    portainer_data_path: "${portainer_data_path}"
    portainer_port: 9443
    portainer_restart_policy: "always"
EOF

    log_success "Created: ${ANSIBLE_DIR}/inventory.yml"
    return 0
}

# Test connectivity
ansible_test() {
    log_info "Testing Ansible connectivity..."
    cd "${ANSIBLE_DIR}" || return 1

    if [[ ! -f "inventory.yml" ]]; then
        log_error "inventory.yml not found"
        return 1
    fi

    if ansible all -m ping -i inventory.yml | tee -a "${LOG_FILE}"; then
        log_success "Connectivity OK"
        return 0
    else
        log_error "Connectivity failed"
        return 1
    fi
}

# Run playbook
ansible_deploy() {
    log_header "Running Ansible Playbook"
    cd "${ANSIBLE_DIR}" || return 1

    if [[ ! -f "inventory.yml" ]]; then
        log_info "Creating inventory..."
        ansible_create_inventory || return 1
    fi

    # VAULT_TOKEN is passed via environment variable (not command line for security)
    if [[ -z "${VAULT_TOKEN:-}" ]]; then
        log_warning "VAULT_TOKEN not set - Vault lookups may fail"
    fi

    log_info "Running: ansible-playbook -i inventory.yml site.yml"

    # Export VAULT_TOKEN so Ansible can access it via environment
    export VAULT_TOKEN
    
    if ansible-playbook -i inventory.yml site.yml | tee -a "${LOG_FILE}"; then
        log_success "Playbook complete"
        
        # Display access information
        local vm_ip
        vm_ip=$(grep "ansible_host:" inventory.yml | awk '{print $2}')
        echo ""
        log_header "Deployment Complete!"
        log_info "SSH: ssh ansible@${vm_ip}"
        log_info "Portainer: https://${vm_ip}:9443"
        log_info ""
        log_info "First-time Portainer setup:"
        log_info "  1. Open https://${vm_ip}:9443 in your browser"
        log_info "  2. Create an admin user and password"
        log_info "  3. Select 'Docker - Manage the local Docker environment'"
        echo ""
        return 0
    else
        log_error "Playbook failed"
        return 1
    fi
}
