#!/usr/bin/env bash
# =============================================================================
# Ansible Functions for VM OpenSUSE Tumbleweed
# =============================================================================

# Prevent multiple sourcing
[[ -n "${_ANSIBLE_SH_LOADED:-}" ]] && return 0
_ANSIBLE_SH_LOADED=1

# Create inventory from Terraform outputs
ansible_create_inventory() {
    log_info "Creating Ansible inventory from Terraform outputs..."

    local iac_tool
    iac_tool=$(get_iac_tool) || return 1
    cd "${TERRAFORM_DIR}" || return 1

    local ip_address
    ip_address=$(${iac_tool} output -raw vm_ip_address 2>/dev/null)

    if [[ -z "${ip_address}" || "${ip_address}" == "null" ]]; then
        log_error "Could not get VM IP from Terraform"
        return 1
    fi

    log_info "VM IP: ${ip_address}"

    cat > "${ANSIBLE_DIR}/inventory.yml" <<EOF
# Generated by deploy.sh at $(date)
all:
  hosts:
    opensuseTumbleweed-vm:
      ansible_host: ${ip_address}
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_python_interpreter: /usr/bin/python3
EOF

    log_success "Created: ${ANSIBLE_DIR}/inventory.yml"
    return 0
}

# Test connectivity
ansible_test() {
    log_info "Testing Ansible connectivity..."
    cd "${ANSIBLE_DIR}" || return 1

    if [[ ! -f "inventory.yml" ]]; then
        log_error "inventory.yml not found"
        return 1
    fi

    if ansible all -m ping -i inventory.yml | tee -a "${LOG_FILE}"; then
        log_success "Connectivity OK"
        return 0
    else
        log_error "Connectivity failed"
        return 1
    fi
}

# Run playbook
ansible_deploy() {
    log_header "Running Ansible Playbook"
    cd "${ANSIBLE_DIR}" || return 1

    if [[ ! -f "inventory.yml" ]]; then
        log_info "Creating inventory..."
        ansible_create_inventory || return 1
    fi

    if [[ -z "${VAULT_TOKEN:-}" ]]; then
        log_warning "VAULT_TOKEN not set - Vault lookups may fail"
    fi

    log_info "Running: ansible-playbook -i inventory.yml site.yml"

    if ansible-playbook -i inventory.yml site.yml | tee -a "${LOG_FILE}"; then
        log_success "Playbook complete"

        local vm_ip
        vm_ip=$(grep "ansible_host:" inventory.yml | awk '{print $2}')
        echo ""
        log_header "Deployment Complete!"
        log_info "SSH Access: ssh ansible@${vm_ip}"
        echo ""
        return 0
    else
        log_error "Playbook failed"
        return 1
    fi
}
